name: Build Binary

on:
  release:
    types:
      - created

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.22.x'
      - name: Install Go dependencies
        run: |
          go get .
      - name: Build
        run: |
          make cave
      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}
      - name: Show files
        run: ls ./bin
      - name: Upload the binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./bin/cave
